Models/ViewModels/UserRoleViewModel.cs
namespace Lab2.Models.ViewModels
{
	public class UserRoleViewModel
	{
		public string UserId { get; set; }
		public string FirstName { get; set; }
		public string LastName { get; set; }
		public string Email { get; set; }
		public IEnumerable<string> Roles { get; set; }
	}
}

Controllers/UserRolesController.cs
using Lab2.Areas.ProjectManagement.Models;
using Lab2.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Lab2.Controllers
{
	//[Authorize(Roles = "SuperAdmin, Admin")]
	public class UserRolesController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly RoleManager<IdentityRole> _roleManager;
		
		public UserRolesController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
		{
			_userManager = userManager;
			_roleManager = roleManager;
		}

        private async Task<IEnumerable<string>> GetUserRolesAsync(ApplicationUser u)
        {
            return new List<string>(await _userManager.GetRolesAsync(u));
        }



        [HttpGet]
		public async Task<IActionResult> Index()
		{
			var users = await _userManager.Users.ToListAsync();
			var userRolesViewModel = new List<UserRoleViewModel>();

			foreach (ApplicationUser u in users) 
			{
				var thisViewModel = new UserRoleViewModel();
				thisViewModel.UserId = u.Id;
				thisViewModel.FirstName = u.FirstName;
				thisViewModel.LastName = u.LastName;
				thisViewModel.Email = u.Email;
				thisViewModel.Roles = await GetUserRolesAsync(u);
				userRolesViewModel.Add(thisViewModel);
			}
			
			return View(userRolesViewModel);
		}



		[HttpGet]
		public async Task<IActionResult> Manage(string userId)
		{
			ViewBag.UserId = userId;
			var user = await _userManager.FindByIdAsync(userId);

			if (user == null)
			{
				ViewBag.ErrorMessage = $"User with ID = {userId} cannot be found.";
				return View("NotFound");
			}

			ViewBag.UserName = user.UserName;
			var model = new List<ManageUserRolesViewModel>();
			
			foreach (var role in _roleManager.Roles)
			{
				var userRolesViewModel = new ManageUserRolesViewModel
				{
					RolesId = role.Id,
					RoleName = role.Name,
				};

				if (await _userManager.IsInRoleAsync(user, role.Name))
				{
					userRolesViewModel.Selected = true;
				}
				else
				{
					userRolesViewModel.Selected = false;
				}

				model.Add(userRolesViewModel);
			}

			return View(model);
		}



		[HttpPost]
		//[Authorize(Roles = "SuperAdmin, Admin")]
		public async Task<IActionResult> Manage(List<ManageUserRolesViewModel> model, string userId)
		{
			var user = await _userManager.FindByIdAsync(userId);
			if (user == null)
			{
				return View();
			}

			var roles = await _userManager.GetRolesAsync(user);
			var result = await _userManager.RemoveFromRolesAsync(user, roles);
			if (!result.Succeeded)
			{
				ModelState.AddModelError("", "Cannot remove user from roles");
				return View(model);
			}

			result = await _userManager
					.AddToRolesAsync(user, model.Where(x => x.Selected).Select(y => y.RoleName));
			if (!result.Succeeded)
			{
				ModelState.AddModelError("", "Cannot add user to roles.");
				return View(model);
			}

			return RedirectToAction("Index");
		}
	}
}

Views/UserRoles/Index.cshtml
@using Lab2.Models.ViewModels
@model List<UserRoleViewModel>

@{
	ViewData["Title"] = "User Role Manager";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>User Roles</h1>

<table class="table table-striped">
	<thead>
		<tr>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Roles</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var user in Model)
		{
			<tr>
				<td>@user.FirstName</td>
				<td>@user.LastName</td>
				<td>@user.Email</td>
				<td>@string.Join(",", user.Roles.ToList())</td>
				<td>
					<a class="btn btn-primary" 
						asp-controller="UserRoles"
						asp-action="Manage" 
						asp-route-userId="@user.UserId">Manage Roles</a>
				</td>
			</tr>
		}
	</tbody>
</table>

Views/UserRoles/Manage.cshtml
@using Lab2.Models.ViewModels
@model List<ManageUserRolesViewModel>
@{
	ViewData["Title"] = "Manage Roles for Users";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
	<div class="card">
		<div class="card-header">
			<h2>Manage User Roles</h2>
			Add/Remove Roles for the User / @ViewBag.UserName
		</div>

		<div class="card-body">
			@for (int i=0; i<Model.Count; i++)
			{
				<div class="form-check m-1">
					<input type="hidden" asp-for="@Model[i].RolesId" />
					<input type="hidden" asp-for="@Model[i].RoleName" />
					<input asp-for="@Model[i].Selected" class="form-check-input" />
					<label class="form-check-label" asp-for="@Model[i].Selected">@Model[i].RoleName</label>
				</div>
			}
			<div asp-validation-summary="All" class="text-danger"></div>
		</div>

		<div class="card-footer">
			<input type="submit" value="Update" class="btn btn-primary" style="width:auto" />
			<a asp-action="Index" class="btn btn-primary" style="width:auto">Cancel</a>
		</div>
	</div>
</form>