Controllers/RoleManagerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Lab2.Models.ViewModels;

namespace Lab2.Controllers
{
    //[Authorize(Roles = "SuperAdmin, Admin")]
    public class RoleManagerController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleManagerController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        [HttpPost]
        //[Authorize(Roles = "SuperAdmin, Admin")]
        public async Task<IActionResult> AddRoles(string roleName)
        {
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }
            
            return RedirectToAction("Index");
        }
    }
}

Views/RoleManager/Index.cshtml
@model List<IdentityRole>
@{
	ViewData["Title"] = "Role Manager";
}

<h1>@ViewData["Title"]</h1>

<form method="post" asp-action="AddRoles" asp-controller="RoleManager">
	<div class="input-group">
		<input name="roleName" class="form-control" />
		<span class="input-group-btn">
			<button class="btn btn-info">Add New Role</button>
		</span>
	</div>
</form>

<table class="table table-striped">
	<thead>
		<tr>
			<th>ID</th>
			<th>Role</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var role in Model)
		{
			<tr>
				<td>@role.Id</td>
				<td>@role.Name</td>
			</tr>
		}
	</tbody>
</table>